### ISSUE TITLE
not running on repl.it

### ISSUE THREAD

**Issue by Mr-aahir** [Sintya4/PREMIUM-DGH-BOT-V2#13]
It shows an error when i run it -
node src/index

/home/runner/PREMIUM-DGH-BOT-V3-1/node_modules/discord-giveaways/src/Manager.js:367
                giveaway.message ??= await giveaway.fetchMessage().catch(() => {});
                                 ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/PREMIUM-DGH-BOT-V3-1/node_modules/discord-giveaways/index.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DGH-BOT-V3@0.0.3 start: `node src/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DGH-BOT-V3@0.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-22T08_45_21_818Z-debug.log

**Comment by Sintya4** [comment]
What _.
there's no way that would happen

**Comment by GioGio03** [comment]
How about that find emoji command? a month has already passed, if you don't have time just say it 😳

**Comment by Rahuletto** [comment]
The user don't have node v16.6.0+ and ??= Is from node v16

**Comment by Sintya4** [comment]
HELLO, JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
