### ISSUE TITLE
i want to run it on replit but it doesn't work

### ISSUE THREAD

**Issue by fadeofficial** [Sintya4/PREMIUM-DGH-BOT-V2#22]
it gives me this error

> node src/index

node:internal/modules/cjs/loader:1179
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/runner/PREMIUM-DGH-BOT-V3-2/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/PREMIUM-DGH-BOT-V3-2/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/PREMIUM-DGH-BOT-V3-2/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v17.3.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tungsted-accordion@1.0.0 start: `node src/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tungsted-accordion@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-17T18_09_02_568Z-debug.log

**Comment by OPM-MASTER** [comment]
`npm uninstall canvas && npm i canvas`

**Comment by Sintya4** [comment]
HELLO, JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
